[settings]
cosine_weight = 0.6
threshold = 0.4
latest_bias = 0.25

[keybindings]
switch_menu = "Ctrl+T"
submit_snippet = "Ctrl+Enter"
current_document_picker = "Ctrl+E"
marked_document_picker = "Ctrl+R"
delete_document_picker = "Ctrl+D"
delete_current_document = "Ctrl+Del"
move_selected_snippet = "Ctrl+F"
delete_selected_snippet = "Del"
update_selected_snippet = "Ctrl+Enter"
